### ISSUE TITLE
14. 在新增页面新增数据后点击确定会有一个"请稍候"的页面显示

### ISSUE THREAD

**Issue by lulugyf** [lulugyf/opendoc#2]
具体在什么模块里需要描述清楚点。

**Comment by lulugyf** [comment]
不清楚说的是什么地方，请增加描述信息

**Comment by lulugyf** [comment]
这个代码在 system.js 里：
function_add.jsp: 143  core.ajax.sendPacketHtml(packet,doAddBack);
=> system.js: 107      sendPacketHtml:function(packet, process ,aysncflag){
              115: loading();
              418: function loading(msg){

**Comment by candlelight520** [comment]
取消该刷新界面
