### ISSUE TITLE
新增管理员角色的工号，仍然无法展示左侧功能树

### ISSUE THREAD

**Issue by candlelight520** [lulugyf/opendoc#7]
我更新版本后试了几次，都还是无法展示，请关总再看看哈

**Comment by lulugyf** [comment]
是添加角色的问题， 新增的管理员角色 rom_sys_role 的 pro_code 字段是 <null>, 导致获取功能树的语句关联不出来。

原因为： 选择类型为管理员后， 产品不能选（把产品那个下拉框 disable了）， 结果submit的时候disable的表单元素不提交

已修正 npage/user/role/role_add.jsp
